---
apiVersion: v1
kind: ConfigMap
metadata:
  name: packagemanage-config
data:
  conf.yaml: |
    - dbname: openeuler-22.03-lts
      src_db_file: https://repo.openeuler.org/openEuler-22.03-LTS/source/
      bin_db_file: https://repo.openeuler.org/openEuler-22.03-LTS/everything/aarch64/
      priority: 1

    - dbname: openeuler-20.03-lts
      src_db_file: https://repo.openeuler.org/openEuler-20.03-LTS/source
      bin_db_file: https://repo.openeuler.org/openEuler-20.03-LTS/everything/aarch64
      priority: 2
    
    - dbname: openeuler-20.03-lts-sp1
      src_db_file: https://repo.openeuler.org/openEuler-20.03-LTS-SP1/source
      bin_db_file: https://repo.openeuler.org/openEuler-20.03-LTS-SP1/everything/aarch64
      priority: 3
    
    - dbname: openeuler-20.03-lts-sp2
      src_db_file: https://repo.openeuler.org/openEuler-20.03-LTS-SP2/source
      bin_db_file: https://repo.openeuler.org/openEuler-20.03-LTS-SP2/everything/aarch64
      priority: 4
    
    - dbname: openeuler-20.03-lts-sp3
      src_db_file: https://repo.openeuler.org/openEuler-20.03-LTS-SP3/source
      bin_db_file: https://repo.openeuler.org/openEuler-20.03-LTS-SP3/everything/aarch64
      priority: 5
    
    - dbname: openeuler-21.09
      src_db_file: https://repo.openeuler.org/openEuler-21.09/source
      bin_db_file: https://repo.openeuler.org/openEuler-21.09/everything/aarch64
      priority: 6
    
    - dbname: openeuler-21.03
      src_db_file: https://repo.openeuler.org/openEuler-21.03/source
      bin_db_file: https://repo.openeuler.org/openEuler-21.03/everything/aarch64
      priority: 7
    
    - dbname: openeuler-20.09
      src_db_file: https://repo.openeuler.org/openEuler-20.09/source
      bin_db_file: https://repo.openeuler.org/openEuler-20.09/everything/aarch64
      priority: 8
    
    - dbname: fedora34
      src_db_file: https://mirrors.huaweicloud.com/fedora/releases/34/Everything/source/tree/
      bin_db_file: https://mirrors.huaweicloud.com/fedora/releases/34/Everything/aarch64/os/
      priority: 9
      
    - dbname: fedora35
      src_db_file: https://mirrors.huaweicloud.com/fedora/releases/35/Everything/source/tree/
      bin_db_file: https://mirrors.huaweicloud.com/fedora/releases/35/Everything/aarch64/os/
      priority: 10
    
    - dbname: fedora36
      src_db_file: https://mirrors.huaweicloud.com/fedora/releases/36/Everything/source/tree/
      bin_db_file: https://mirrors.huaweicloud.com/fedora/releases/36/Everything/aarch64/os/
      priority: 11
    
    - dbname: openeuler-22.03-lts-epol
      src_db_file: https://repo.openeuler.org/openEuler-22.03-LTS/EPOL/main/source/
      bin_db_file: https://repo.openeuler.org/openEuler-22.03-LTS/EPOL/main/aarch64/
      priority: 12
    
    - dbname: openeuler-20.03-lts-sp1-epol
      src_db_file: https://repo.openeuler.org/openEuler-20.03-LTS-SP1/EPOL/source/
      bin_db_file: https://repo.openeuler.org/openEuler-20.03-LTS-SP1/EPOL/aarch64/
      priority: 13
    
    - dbname: openeuler-20.03-lts-sp2-epol
      src_db_file: https://repo.openeuler.org/openEuler-20.03-LTS-SP2/EPOL/main/source/
      bin_db_file: https://repo.openeuler.org/openEuler-20.03-LTS-SP2/EPOL/main/aarch64/
      priority: 14
    
    - dbname: openeuler-20.03-lts-sp3-epol
      src_db_file: https://repo.openeuler.org/openEuler-20.03-LTS-SP3/EPOL/main/source/
      bin_db_file: https://repo.openeuler.org/openEuler-20.03-LTS-SP3/EPOL/main/aarch64/
      priority: 15
    
    - dbname: openeuler-21.09-epol
      src_db_file: https://repo.openeuler.org/openEuler-21.09/EPOL/main/source/
      bin_db_file: https://repo.openeuler.org/openEuler-21.09/EPOL/main/aarch64/
      priority: 16
    
    - dbname: openeuler-21.03-epol
      src_db_file: https://repo.openeuler.org/openEuler-21.03/EPOL/source/
      bin_db_file: https://repo.openeuler.org/openEuler-21.03/EPOL/aarch64/
      priority: 17

  package.ini: |
    [SYSTEM]
    ; Configuration file path for data initialization
    init_conf_path=/etc/pkgship/conf.yaml
    
    ; Ordinary user query port, only the right to query data, no permission to write data
        
    query_port=8090
    
    ; IP address path with permission to query data
    
    query_ip_addr=0.0.0.0
    
    ; The address of the remote service, the command line can directly 
    ; call the remote service to complete the data request
    remote_host=https://api.openeuler.org/pkgmanage
    
    ; A temporary directory for files downloaded from the network that are cleaned periodically
    ; The recommended free space in this dir is 1G
    temporary_directory=/opt/pkgship/tmp/
    
    [LOG]
    ; Custom log storage path
    log_path=/var/log/pkgship/
    
    ; Logging level
    ; The log level option value can only be as follows
    ; INFO DEBUG WARNING ERROR CRITICAL
    log_level=INFO
    
    ; Maximum capacity of each file, the unit is byte, default is 30M
    max_bytes=31457280
    
    ; Number of old logs to keep;default is 30
    backup_count=30
    
    [UWSGI]
    ; Operation log storage path
    daemonize=/var/log/pkgship-operation/uwsgi.log
    ; The data size transferred from back to forth
    buffer-size=65536
    ; HTTP Connection time
    http-timeout=600
    ; Server response time
    harakiri=600
    
    [REDIS]
    ;The address of the Redis cache server can be either a published
    ;domain or an IP address that can be accessed normally
    ;The link address defaults to 127.0.0.1
    redis_host=127.0.0.1
    
    ;Redis cache server link port number, default is 6379
    redis_port=6379
    
    ;Maximum number of connections allowed by RedIS server at one time
    redis_max_connections=10
    
    [DATABASE]
    ;The database engines supported in the system is sqlite database by default
    database_engine_type=elastic
    
    ;Default ip address of database
    database_host=127.0.0.1
    
    ;Default port of database
    database_port=9200

    [PANEL]

    ;obs base path
    obs_host=http://117.78.1.88/

    ;obs user name
    ;obs_account=

    ;obs user password
    ;obs_password=

    ;gitee token
    ;git_token=

    panel_port=8091

  timed_task.yaml: |
    - type: synchronous_task
      scheduler: AsyncIOScheduler
      tasks:
        - name: sync_rpm_build
          trigger: cron
          day_of_week: 
          enable: true
          hour: 
          minute: '*/10'
          second: 
        - name: sync_iso_build
          trigger: cron
          day_of_week: 0
          enable: true
          hour: 2
          minute: 0
          second: 0
        - name: sync_sig
          trigger: cron
          day_of_week: 0
          enable: true
          hour: 1
          minute: 5
          second: 0
        - name: sync_version
          trigger: cron
          enable: true
          day_of_week: 0
          hour: 2
          minute: 10
          second: 0
        - name: sync_branch
          trigger: cron
          enable: true
          day_of_week: 0
          hour: 3
          minute: 5
          second: 0
    - type: send_email_task
      scheduler: AsyncIOScheduler
      tasks:
        - name: send_email
          trigger: cron
          enable: true
          day_of_week: 0
          hour: 4
          minute: 0
          second: 0

